iconv -f ISO8859-2 -t UTF-8 -o tade.kimenet.tsv tade.tsv &&
sed -i -e 's/NP<CAS<ACC>>/[Acc]/g' \
       -e 's/NP<CAS<DAT>>/[Dat]/g' \
       -e 's/NP<CAS<INS>>/[Ins]/g' \
       -e 's/NP<CAS<CAU>>/[Cau]/g' \
       -e 's/NP<CAS<TRA>>/[Transl]/g' \
       -e 's/NP<CAS<INE>>/[Ine]/g' \
       -e 's/NP<CAS<SUE>>/[Supe]/g' \
       -e 's/NP<CAS<ADE>>/[Ade]/g' \
       -e 's/NP<CAS<ILL>>/[Ill]/g' \
       -e 's/NP<CAS<SBL>>/[Subl]/g' \
       -e 's/NP<CAS<ALL>>/[All]/g' \
       -e 's/NP<CAS<TER>>/[Ter]/g' \
       -e 's/NP<CAS<ELA>>/[Ela]/g' \
       -e 's/NP<CAS<DEL>>/[Del]/g' \
       -e 's/NP<CAS<ABL>>/[Abl]/g' \
       -e 's/NP<CAS<FOR>>/[EssFor]/g' \
       -e 's/NP<CAS<ESS>>/[Ess]/g' \
       -e 's/NP<CAS<TEM>>/[Temp]/g' \
       -e 's/PP<\([^>]*\)>/=\L\1/g' \
       -e 's/+/|/g' \
       -e 's/_/ /g' tade.kimenet.tsv
